Repository Advanced-Command-Handler/Advanced-Command-Handler, pull requests merged in 2020-12, with the labels that each got.

#40 Converted to Typescript.
  .gitignore
  .npmignore
  README.md
  assets/presentation.txt
  classes/Client.js
  classes/Command.js
  classes/CommandHandler.js
  classes/CommandHandlerError.js
  index.js
  package-lock.json
  package.json
  src/classes/AdvancedClient.ts
  src/classes/Command.ts
  src/classes/CommandHandler.ts
  src/classes/CommandHandlerError.ts
  src/index.ts
  src/utils/Logger.ts
  src/utils/argError.ts
  src/utils/getThing.ts
  tsconfig.json
  utils/BetterEmbed.js
  utils/Logger.js
  utils/argError.js
  utils/getThing.js
Labels: dependencies, enhancement, help wanted

#41 Feat/command/channels only
  src/classes/Command.ts
Labels: enhancement, feature_request

#43 Make CommandHandler#launch async and remove encapsulation anonym func…
  src/classes/CommandHandler.ts
Labels: enhancement
